### ISSUE TITLE
Update Docker image to use new node addition API

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/docker#29]
Our image still relies upon `pg_worker_list.conf`, so we should update that to use master_add_node/master_remove_node.

**Comment by furkansahin** [comment]
Hey @sumedhpathak after playing around with the image, I tried to come up with a solution. 
Currently, we rely on an open source project [jwilder/docker-gen](https://github.com/jwilder/docker-gen) to create the pg_worker_list.conf file.

What docker-gen (our repo [workerlist-gen](https://github.com/citusdata/workerlist-gen)) does is basically if there is an event which fits in .tmpl file, it writes/deletes the event data (worker_name and port) from the conf file. Hence, we use that project to add or remove workers from our coordinator node.

Firstly, I tried to play around docker-gen and modify it so that it does not write any file but just calls master_add_node/master_remove_node. However, I do not know Go and I think that the project is much more complicated than our needs.

Hopefully, docker has a python API and it allows us to follow the events. I created a simple script which is in a very pre-mature stage but still I wanted to share it with you. You can see it [here](https://github.com/citusdata/workerlist-gen/blob/furkan-WIP/manager.py). Basically, I follow the events by using docker api and if there is a start/die for any of our workers, I query the corresponding SQL. 

Since I am pretty new to docker, I did not integrate it with our own image yet. However, it manages successfully our coordinator and workers when I run it as a separate process.

I just wanted to share the situation I am in right now. If you and @jasonmp85 find this approach acceptable and worthy to spend more time so that it is integrated with our image, I am going to continue. Additionally, I see that our docker repo is able to work with docker-cloud too. I couldn't imagine if this solution would also work for docker-cloud or not.

Any feedback is appreciated.
